// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBGtQJ0VrJSgqhDPRlHQQzcsyd1nmSBm4',
    appId: '1:1029354322178:web:126fadd6541cd2aa5c6a1b',
    messagingSenderId: '1029354322178',
    projectId: 'shivsumantrainer',
    authDomain: 'shivsumantrainer.firebaseapp.com',
    databaseURL: 'https://shivsumantrainer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivsumantrainer.appspot.com',
    measurementId: 'G-40N9NTTC97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWxDU3gdy6QFainXWAkV4RY4HsJIqimU',
    appId: '1:1029354322178:android:b806bec923f7687a5c6a1b',
    messagingSenderId: '1029354322178',
    projectId: 'shivsumantrainer',
    databaseURL: 'https://shivsumantrainer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivsumantrainer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhPP-GyzkO0jN8LeUvfIbgyGW1TVMnovE',
    appId: '1:1029354322178:ios:ccb762d6953d50a95c6a1b',
    messagingSenderId: '1029354322178',
    projectId: 'shivsumantrainer',
    databaseURL: 'https://shivsumantrainer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivsumantrainer.appspot.com',
    iosBundleId: 'com.example.carTrainerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhPP-GyzkO0jN8LeUvfIbgyGW1TVMnovE',
    appId: '1:1029354322178:ios:ccb762d6953d50a95c6a1b',
    messagingSenderId: '1029354322178',
    projectId: 'shivsumantrainer',
    databaseURL: 'https://shivsumantrainer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivsumantrainer.appspot.com',
    iosBundleId: 'com.example.carTrainerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBGtQJ0VrJSgqhDPRlHQQzcsyd1nmSBm4',
    appId: '1:1029354322178:web:7d64831534e2fdf25c6a1b',
    messagingSenderId: '1029354322178',
    projectId: 'shivsumantrainer',
    authDomain: 'shivsumantrainer.firebaseapp.com',
    databaseURL: 'https://shivsumantrainer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shivsumantrainer.appspot.com',
    measurementId: 'G-2H7Q06F3FH',
  );

}